version: '2'

services:
  nginx:
    build: nginx
    env_file: docker-env
    ports:
      - "80:80"
    volumes:
      - ~/www:/var/www/html
    tty: true

  php:
    build: php
    env_file: docker-env
    ports:
      - "9000:9000"
    volumes:
      - ~/www:/var/www/html
    tty: true

  mysql:
    image: mariadb:latest
    env_file: docker-env
    ports:
      - "3306:3306"
    tty: true

  node:
    image: node:latest
    env_file: docker-env
    ports:
      - "8888:8888"
    tty: true
